alias gp='export http_proxy=http://127.0.0.1:7890 https_proxy=http://127.0.0.1:7890'
alias unp='unset http_proxy https_proxy'
alias ..='cd ..'
alias ...='cd ../..'
alias ls='lsd'
alias l='ls -l'
alias ll='ls -l'
alias lla='ls -la'
alias la='ls -a'
alias lt='ls --tree'
alias nv='nvim'
alias lg='lazygit'
alias kc='kubectl'
alias cg='cargo'
alias grep='rg'
alias find='fd'
alias tr='trash'
alias up='brew update && brew upgrade && zi update --parallel'
