alias gp='export http_proxy=http://127.0.0.1:7890 https_proxy=http://127.0.0.1:7890'
alias unp='unset http_proxy https_proxy'
alias ls='lsd'
alias l='ls -l'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'
alias nv='nvim'
alias lg='lazygit'
alias kc='kubectl'
alias cg='cargo'

